# Generated by Django 5.2.1 on 2025-05-19 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('rejected', 'Отклонена')], default='new', max_length=10, verbose_name='Статус'),
        ),
    ]
